default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: admin
  password: 1401Moon
  host: database-1.cgu4tvllynsp.ap-northeast-1.rds.amazonaws.com
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: runteq_production